// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJqeM4imCcCxwkvQ9aC34E68yEP6TbH4k',
    appId: '1:587650482104:web:b17941f8e6e5a3712e994d',
    messagingSenderId: '587650482104',
    projectId: 'project-bind-28042',
    authDomain: 'project-bind-28042.firebaseapp.com',
    databaseURL: 'https://project-bind-28042-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'project-bind-28042.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0TFEUHydPYKOE9gemDgxH5eBIirrvYPE',
    appId: '1:587650482104:android:8a5a7d06cd45b6d02e994d',
    messagingSenderId: '587650482104',
    projectId: 'project-bind-28042',
    databaseURL: 'https://project-bind-28042-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'project-bind-28042.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs4A1MRjqaGeK18p5nBo10Q5hacPXKkhE',
    appId: '1:587650482104:ios:1a2ebab5d963fdb02e994d',
    messagingSenderId: '587650482104',
    projectId: 'project-bind-28042',
    databaseURL: 'https://project-bind-28042-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'project-bind-28042.appspot.com',
    iosClientId: '587650482104-hpv084qp4knqt4cnl2ldf667eei2lbtq.apps.googleusercontent.com',
    iosBundleId: 'com.anony.bind',
  );
}
